create table beers(name char(40) primary key, ABV float, IBU float);
insert into beer values ('Heineken', 4.4, 18.0);
insert into beer values ('Lados Ipa', 5.3, 40.5);
insert into beer values ('Corona', 4.7, 17.1);
insert into beer values ('87 Peroni Pilsner',4.9, 29.8);
insert into beer values ('Caskolsch Pale Ale', 5.4, 34.6);
insert into beer values ('Coors Lite', 3.2, 13.2);
insert into beer values ('Asahi', 4.6, 32.5);
insert into beer values ('Miller German Pilsener', 4.5, 26.8);
insert into beer values ('Sm Skol Fredrik Jonsson', 6.6, 46.7);
insert into beer values ('Grand Cru', 9.4, 13.5);
insert into beer values ('Saison De La Place', 5.2, 36.4);
insert into beer values ('Saison', 8.9, 27.5);
insert into beer values ('How Rye Am I', 8.0, 25.1);
insert into beer values ('First Snow', 9.0, 36.9);
insert into beer values ('Walts Sam Adams Octoberfest', 5.4, 16.2);
insert into beer values ('Becks Clone', 5.4, 29.6);
insert into beer values ('The Millers Toll', 9.9, 56.7);
insert into beer values ('Keystone', 4.9, 12.2);
insert into beer values ('Natural Redhead', 5.8, 23.6);
